### ISSUE TITLE
Document ES syntax level requirements

### ISSUE THREAD

**Issue by ankon** [Collaborne/eslint-config-collaborne#2]
Using these rules in a ES6 project leads to 
```
  3:1  error  Parsing error: The keyword 'const' is reserved
```

When using the configuration with ES6 one needs to use a .eslintrc.json with explicitly specifying the parser version:
```json
{
	"extends": "collaborne",
	"parserOptions": {
		"ecmaVersion": 6
	}
}
```

**Comment by ronnyroeller** [comment]
Should we just add this to eslint-config-collaborne/index.js itself?

**Comment by ankon** [comment]
TBH: I expected that ... or better, I expected that I just use the configuration and it works. Having to look up why eslint complained about 'const' was weird.

**Comment by ankon** [comment]
Closing: This is pretty much taken care of nowadays.
